name: Links Check

on:
  repository_dispatch:
  workflow_dispatch:
  # runs every monday at 7 am
  schedule:
    - cron: "0 7 * * 1"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        # checks all markdown files from /content including all subfolders
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/workflows/markdown.links.config.json'
          folder-path: 'content/'

      - uses: actions/checkout@main
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        # checks all markdown files from root (README.md) but ignores subfolders
        with:
          use-quiet-mode: 'yes'
          max-depth: 0
